title: WxManBran
description: Tropical weather updates by Weather Man Bran
url: "https://brandankeen.github.io"   # change to your domain later
baseurl: "/WxManBran"                   # remove when you add a custom domain
theme: minima
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  storms:
    output: true
    permalink: /storms/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
  - scope:
      path: ""
      type: "storms"
    values:
      layout: default
